apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  type: ClusterIP      ## or LoadBalancer(supported by Cloud providers like AWS)    
  selector:
    run: my-nginx
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
    # Optional field
    # By default and for convenience, the Kubernetes control plane will allocate a port from a range (default: 30000-32767)
#    nodePort: 30001
